In [21]:
pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\jaffu\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\jaffu\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in c:\users\jaffu\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\jaffu\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\jaffu\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: C:\Users\jaffu\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, roc_auc_score
)

In [4]:
df = pd.read_csv(r"C:\Users\jaffu\Desktop\Ml projects\test_Y3wMUE5_7gLdaTN.csv")
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [5]:
df.head(5)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    str
 1   Gender             356 non-null    str
 2   Married            367 non-null    str
 3   Dependents         357 non-null    str
 4   Education          367 non-null    str
 5   Self_Employed      344 non-null    str
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    str
dtypes: float64(3), int64(2), str(7)
memory usage: 34.5 KB

In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

In [8]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

In [9]:
print("=" * 55)
print("  LOAN APPROVAL CLASSIFICATION PROJECT")
print("=" * 55)

df = pd.read_csv(r"C:\Users\jaffu\Desktop\Ml projects\test_Y3wMUE5_7gLdaTN.csv")

print(f"\n[INFO] Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns")

=======================================================
  LOAN APPROVAL CLASSIFICATION PROJECT
=======================================================

[INFO] Dataset loaded: 367 rows, 12 columns

In [10]:
print("\n" + "─" * 55)
print("  STEP 1: EXPLORATORY DATA ANALYSIS")
print("─" * 55)

print("\n[Dataset Info]")
df.info()

print("\n[Missing Values per Column]")
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"Missing": missing, "Percentage (%)": missing_pct})
print(missing_df[missing_df["Missing"] > 0])

print("\n[Basic Statistics - Numerical Columns]")
print(df.describe().round(2))

print("\n[Categorical Column Value Counts]")
cat_cols = df.select_dtypes(include="object").columns.tolist()
for col in cat_cols:
    if col != "Loan_ID":
        print(f"\n  >> {col}:")
        print(df[col].value_counts().to_string())

───────────────────────────────────────────────────────
  STEP 1: EXPLORATORY DATA ANALYSIS
───────────────────────────────────────────────────────

[Dataset Info]
<class 'pandas.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    str
 1   Gender             356 non-null    str
 2   Married            367 non-null    str
 3   Dependents         357 non-null    str
 4   Education          367 non-null    str
 5   Self_Employed      344 non-null    str
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    str
dtypes: float64(3), int64(2), str(7)
memory usage: 34.5 KB

[Missing Values per Column]
                  Missing  Percentage (%)
Gender                 11            3.00
Dependents             10            2.72
Self_Employed          23            6.27
LoanAmount              5            1.36
Loan_Amount_Term        6            1.63
Credit_History         29            7.90

[Basic Statistics - Numerical Columns]
       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count           367.00             367.00      362.00            361.00
mean           4805.60            1569.58      136.13            342.54
std            4910.69            2334.23       61.37             65.16
min               0.00               0.00       28.00              6.00
25%            2864.00               0.00      100.25            360.00
50%            3786.00            1025.00      125.00            360.00
75%            5060.00            2430.50      158.00            360.00
max           72529.00           24000.00      550.00            480.00

       Credit_History
count          338.00
mean             0.83
std              0.38
min              0.00
25%              1.00
50%              1.00
75%              1.00
max              1.00

[Categorical Column Value Counts]

  >> Gender:
Gender
Male      286
Female     70

  >> Married:
Married
Yes    233
No     134

  >> Dependents:
Dependents
0     200
2      59
1      58
3+     40

  >> Education:
Education
Graduate        283
Not Graduate     84

  >> Self_Employed:
Self_Employed
No     307
Yes     37

  >> Property_Area:
Property_Area
Urban        140
Semiurban    116
Rural        111

C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2837553711.py:18: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include="object").columns.tolist()

In [11]:
print("\n" + "─" * 55)
print("  STEP 2: DATA PREPROCESSING")
print("─" * 55)

df_clean = df.copy()
df_clean.drop(columns=["Loan_ID"], inplace=True)

───────────────────────────────────────────────────────
  STEP 2: DATA PREPROCESSING
───────────────────────────────────────────────────────

In [12]:
print("\n[Filling Missing Values...]")
df_clean["Gender"].fillna(df_clean["Gender"].mode()[0], inplace=True)
df_clean["Dependents"].fillna(df_clean["Dependents"].mode()[0], inplace=True)
df_clean["Self_Employed"].fillna(df_clean["Self_Employed"].mode()[0], inplace=True)
df_clean["LoanAmount"].fillna(df_clean["LoanAmount"].median(), inplace=True)
df_clean["Loan_Amount_Term"].fillna(df_clean["Loan_Amount_Term"].mode()[0], inplace=True)
df_clean["Credit_History"].fillna(df_clean["Credit_History"].mode()[0], inplace=True)

print("  ✓ Missing values filled successfully")
print(f"  ✓ Remaining nulls: {df_clean.isnull().sum().sum()}")

[Filling Missing Values...]
  ✓ Missing values filled successfully
  ✓ Remaining nulls: 84

C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2573300606.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Gender"].fillna(df_clean["Gender"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2573300606.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Dependents"].fillna(df_clean["Dependents"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2573300606.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Self_Employed"].fillna(df_clean["Self_Employed"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2573300606.py:5: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["LoanAmount"].fillna(df_clean["LoanAmount"].median(), inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2573300606.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Loan_Amount_Term"].fillna(df_clean["Loan_Amount_Term"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2573300606.py:7: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Credit_History"].fillna(df_clean["Credit_History"].mode()[0], inplace=True)

In [13]:
print("\n[Encoding Categorical Columns...]")
le = LabelEncoder()
encode_cols = ["Gender", "Married", "Dependents", "Education", "Self_Employed", "Property_Area"]
for col in encode_cols:
    df_clean[col] = le.fit_transform(df_clean[col].astype(str))
    print(f"  ✓ Encoded: {col}")

[Encoding Categorical Columns...]
  ✓ Encoded: Gender
  ✓ Encoded: Married
  ✓ Encoded: Dependents
  ✓ Encoded: Education
  ✓ Encoded: Self_Employed
  ✓ Encoded: Property_Area

In [14]:
print("=" * 55)
print("  LOAN APPROVAL CLASSIFICATION PROJECT")
print("=" * 55)

df = pd.read_csv(r"C:\Users\jaffu\Desktop\Ml projects\test_Y3wMUE5_7gLdaTN.csv")

print(f"\n[INFO] Dataset loaded: {df.shape[0]} rows, {df.shape[1]} columns")

=======================================================
  LOAN APPROVAL CLASSIFICATION PROJECT
=======================================================

[INFO] Dataset loaded: 367 rows, 12 columns

In [15]:
print("\n" + "─" * 55)
print("  STEP 1: EXPLORATORY DATA ANALYSIS")
print("─" * 55)

print("\n[Dataset Info]")
df.info()

print("\n[Missing Values per Column]")
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_df = pd.DataFrame({"Missing": missing, "Percentage (%)": missing_pct})
print(missing_df[missing_df["Missing"] > 0])

print("\n[Basic Statistics - Numerical Columns]")
print(df.describe().round(2))

print("\n[Categorical Column Value Counts]")
cat_cols = df.select_dtypes(include="object").columns.tolist()
for col in cat_cols:
    if col != "Loan_ID":
        print(f"\n  >> {col}:")
        print(df[col].value_counts().to_string())

───────────────────────────────────────────────────────
  STEP 1: EXPLORATORY DATA ANALYSIS
───────────────────────────────────────────────────────

[Dataset Info]
<class 'pandas.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    str
 1   Gender             356 non-null    str
 2   Married            367 non-null    str
 3   Dependents         357 non-null    str
 4   Education          367 non-null    str
 5   Self_Employed      344 non-null    str
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    str
dtypes: float64(3), int64(2), str(7)
memory usage: 34.5 KB

[Missing Values per Column]
                  Missing  Percentage (%)
Gender                 11            3.00
Dependents             10            2.72
Self_Employed          23            6.27
LoanAmount              5            1.36
Loan_Amount_Term        6            1.63
Credit_History         29            7.90

[Basic Statistics - Numerical Columns]
       ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count           367.00             367.00      362.00            361.00
mean           4805.60            1569.58      136.13            342.54
std            4910.69            2334.23       61.37             65.16
min               0.00               0.00       28.00              6.00
25%            2864.00               0.00      100.25            360.00
50%            3786.00            1025.00      125.00            360.00
75%            5060.00            2430.50      158.00            360.00
max           72529.00           24000.00      550.00            480.00

       Credit_History
count          338.00
mean             0.83
std              0.38
min              0.00
25%              1.00
50%              1.00
75%              1.00
max              1.00

[Categorical Column Value Counts]

  >> Gender:
Gender
Male      286
Female     70

  >> Married:
Married
Yes    233
No     134

  >> Dependents:
Dependents
0     200
2      59
1      58
3+     40

  >> Education:
Education
Graduate        283
Not Graduate     84

  >> Self_Employed:
Self_Employed
No     307
Yes     37

  >> Property_Area:
Property_Area
Urban        140
Semiurban    116
Rural        111

C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\2837553711.py:18: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_cols = df.select_dtypes(include="object").columns.tolist()

In [16]:
print("\n" + "─" * 55)
print("  STEP 2: DATA PREPROCESSING")
print("─" * 55)

df_clean = df.copy()
df_clean.drop(columns=["Loan_ID"], inplace=True)

# Fill missing values
print("\n[Filling Missing Values...]")
df_clean["Gender"].fillna(df_clean["Gender"].mode()[0], inplace=True)
df_clean["Dependents"].fillna(df_clean["Dependents"].mode()[0], inplace=True)
df_clean["Self_Employed"].fillna(df_clean["Self_Employed"].mode()[0], inplace=True)
df_clean["LoanAmount"].fillna(df_clean["LoanAmount"].median(), inplace=True)
df_clean["Loan_Amount_Term"].fillna(df_clean["Loan_Amount_Term"].mode()[0], inplace=True)
df_clean["Credit_History"].fillna(df_clean["Credit_History"].mode()[0], inplace=True)

print("  ✓ Missing values filled successfully")
print(f"  ✓ Remaining nulls: {df_clean.isnull().sum().sum()}")

# Encode categorical columns
print("\n[Encoding Categorical Columns...]")
le = LabelEncoder()
encode_cols = ["Gender", "Married", "Dependents", "Education", "Self_Employed", "Property_Area"]
for col in encode_cols:
    df_clean[col] = le.fit_transform(df_clean[col].astype(str))
    print(f"  ✓ Encoded: {col}")

───────────────────────────────────────────────────────
  STEP 2: DATA PREPROCESSING
───────────────────────────────────────────────────────

[Filling Missing Values...]
  ✓ Missing values filled successfully
  ✓ Remaining nulls: 84

[Encoding Categorical Columns...]
  ✓ Encoded: Gender
  ✓ Encoded: Married
  ✓ Encoded: Dependents
  ✓ Encoded: Education
  ✓ Encoded: Self_Employed
  ✓ Encoded: Property_Area

C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\1558962854.py:10: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Gender"].fillna(df_clean["Gender"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\1558962854.py:11: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Dependents"].fillna(df_clean["Dependents"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\1558962854.py:12: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Self_Employed"].fillna(df_clean["Self_Employed"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\1558962854.py:13: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["LoanAmount"].fillna(df_clean["LoanAmount"].median(), inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\1558962854.py:14: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Loan_Amount_Term"].fillna(df_clean["Loan_Amount_Term"].mode()[0], inplace=True)
C:\Users\jaffu\AppData\Local\Temp\ipykernel_21220\1558962854.py:15: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df_clean["Credit_History"].fillna(df_clean["Credit_History"].mode()[0], inplace=True)

In [17]:
print("\n[NOTE] No 'Loan_Status' column found in test file.")
print("       Simulating target using Credit_History + LoanAmount for demo...")

np.random.seed(42)
df_clean["Loan_Status"] = (
    (df_clean["Credit_History"] == 1) &
    (df_clean["LoanAmount"] < df_clean["LoanAmount"].median() + 50)
).astype(int)

# Add slight randomness to make it realistic
noise = np.random.choice([0, 1], size=len(df_clean), p=[0.85, 0.15])
df_clean["Loan_Status"] = ((df_clean["Loan_Status"] + noise) > 0).astype(int)

print(f"\n[Simulated Target Distribution]")
counts = df_clean["Loan_Status"].value_counts()
print(f"  Approved (1): {counts.get(1, 0)} ({counts.get(1, 0)/len(df_clean)*100:.1f}%)")
print(f"  Rejected (0): {counts.get(0, 0)} ({counts.get(0, 0)/len(df_clean)*100:.1f}%)")

[NOTE] No 'Loan_Status' column found in test file.
       Simulating target using Credit_History + LoanAmount for demo...

[Simulated Target Distribution]
  Approved (1): 248 (67.6%)
  Rejected (0): 119 (32.4%)

In [18]:
print("\n" + "─" * 55)
print("  STEP 3: TRAIN-TEST SPLIT & SCALING")
print("─" * 55)

X = df_clean.drop(columns=["Loan_Status"])
y = df_clean["Loan_Status"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print(f"\n  Training samples : {len(X_train)}")
print(f"  Testing  samples : {len(X_test)}")
print(f"  Features         : {X.shape[1]}")

───────────────────────────────────────────────────────
  STEP 3: TRAIN-TEST SPLIT & SCALING
───────────────────────────────────────────────────────

  Training samples : 293
  Testing  samples : 74
  Features         : 11

In [19]:
print("\n" + "─" * 55)
print("  STEP 4: MODEL TRAINING & EVALUATION")
print("─" * 55)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest"      : RandomForestClassifier(n_estimators=100, random_state=42),
}

results = {}
for name, model in models.items():
    print(f"\n>>> Training: {name}")

    # Choose scaled or unscaled based on model type
    X_tr = X_train_scaled if name == "Logistic Regression" else X_train
    X_te = X_test_scaled  if name == "Logistic Regression" else X_test

    model.fit(X_tr, y_train)
    y_pred = model.predict(X_te)
    y_prob = model.predict_proba(X_te)[:, 1]

    acc      = accuracy_score(y_test, y_pred)
    roc_auc  = roc_auc_score(y_test, y_prob)
    cv_score = cross_val_score(model, X_tr, y_train, cv=5, scoring="accuracy").mean()

    results[name] = {"Accuracy": acc, "ROC-AUC": roc_auc, "CV Accuracy": cv_score}

    print(f"  ✓ Accuracy      : {acc*100:.2f}%")
    print(f"  ✓ ROC-AUC Score : {roc_auc:.4f}")
    print(f"  ✓ CV Accuracy   : {cv_score*100:.2f}% (5-fold)")

    print(f"\n  [Confusion Matrix - {name}]")
    cm = confusion_matrix(y_test, y_pred)
    print(f"  {'':>15} Predicted 0  Predicted 1")
    print(f"  Actual 0   : {cm[0][0]:>8}     {cm[0][1]:>8}")
    print(f"  Actual 1   : {cm[1][0]:>8}     {cm[1][1]:>8}")

    print(f"\n  [Classification Report - {name}]")
    print(classification_report(y_test, y_pred, target_names=["Rejected", "Approved"]))

───────────────────────────────────────────────────────
  STEP 4: MODEL TRAINING & EVALUATION
───────────────────────────────────────────────────────

>>> Training: Logistic Regression

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
print("\n" + "─" * 55)
print("  STEP 4: MODEL TRAINING & EVALUATION")
print("─" * 55)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Random Forest"      : RandomForestClassifier(n_estimators=100, random_state=42),
}

results = {}
for name, model in models.items():
    print(f"\n>>> Training: {name}")

───────────────────────────────────────────────────────
  STEP 4: MODEL TRAINING & EVALUATION
───────────────────────────────────────────────────────

>>> Training: Logistic Regression

>>> Training: Random Forest

In [ ]:
# Choose scaled data only for Logistic Regression
X_tr = X_train_scaled if name == "Logistic Regression" else X_train
X_te = X_test_scaled if name == "Logistic Regression" else X_test

# Train model
model.fit(X_tr, y_train)

# Predictions
y_pred = model.predict(X_te)
y_prob = model.predict_proba(X_te)[:, 1]

# Metrics
acc = accuracy_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)
cv_score = cross_val_score(model, X_tr, y_train, cv=5, scoring="accuracy").mean()

# Store results
results[name] = {
    "Accuracy": acc,
    "ROC-AUC": roc_auc,
    "CV Accuracy": cv_score
}

# Print results
print(f"  ✓ Accuracy      : {acc*100:.2f}%")
print(f"  ✓ ROC-AUC Score : {roc_auc:.4f}")
print(f"  ✓ CV Accuracy   : {cv_score*100:.2f}% (5-fold)")

# Confusion Matrix
print(f"\n  [Confusion Matrix - {name}]")
cm = confusion_matrix(y_test, y_pred)
print(f"  {'':>15} Predicted 0  Predicted 1")
print(f"  Actual 0   : {cm[0][0]:>8}     {cm[0][1]:>8}")
print(f"  Actual 1   : {cm[1][0]:>8}     {cm[1][1]:>8}")

# Classification Report
print(f"\n  [Classification Report - {name}]")
print(classification_report(y_test, y_pred, target_names=["Rejected", "Approved"]))

  ✓ Accuracy      : 91.89%
  ✓ ROC-AUC Score : 0.9525
  ✓ CV Accuracy   : 88.38% (5-fold)

  [Confusion Matrix - Random Forest]
                  Predicted 0  Predicted 1
  Actual 0   :       22            2
  Actual 1   :        4           46

  [Classification Report - Random Forest]
              precision    recall  f1-score   support

    Rejected       0.85      0.92      0.88        24
    Approved       0.96      0.92      0.94        50

    accuracy                           0.92        74
   macro avg       0.90      0.92      0.91        74
weighted avg       0.92      0.92      0.92        74

In [ ]:
print("\n" + "─" * 55)
print("  STEP 5: FEATURE IMPORTANCE (Random Forest)")
print("─" * 55)

rf_model = models["Random Forest"]
importances = pd.Series(rf_model.feature_importances_, index=X.columns)
importances = importances.sort_values(ascending=False)

print("\n  Feature Importance Ranking:")
for i, (feat, imp) in enumerate(importances.items(), 1):
    bar = "█" * int(imp * 80)
    print(f"  {i:>2}. {feat:<22} {bar} {imp:.4f}")

───────────────────────────────────────────────────────
  STEP 5: FEATURE IMPORTANCE (Random Forest)
───────────────────────────────────────────────────────

  Feature Importance Ranking:
   1. LoanAmount             ████████████████████████████████ 0.4030
   2. Credit_History         ██████████████████████ 0.2834
   3. ApplicantIncome        █████████ 0.1203
   4. CoapplicantIncome      █████ 0.0630
   5. Dependents             ██ 0.0328
   6. Property_Area          █ 0.0220
   7. Married                █ 0.0173
   8. Loan_Amount_Term       █ 0.0171
   9. Self_Employed          █ 0.0167
  10. Gender                 █ 0.0128
  11. Education               0.0117

In [ ]:
print("\n" + "=" * 55)
print("  FINAL SUMMARY")
print("=" * 55)

best_model = max(results, key=lambda k: results[k]["Accuracy"])
print(f"\n  Best Performing Model : {best_model}")
for k, v in results.items():
    print(f"\n  {k}:")
    print(f"    Accuracy    : {v['Accuracy']*100:.2f}%")
    print(f"    ROC-AUC     : {v['ROC-AUC']:.4f}")
    print(f"    CV Accuracy : {v['CV Accuracy']*100:.2f}%")

print("\n  [NEXT STEPS]")
print("  1. Load the actual TRAINING dataset with Loan_Status labels")
print("  2. Tune hyperparameters (GridSearchCV / RandomizedSearchCV)")
print("  3. Try XGBoost or Gradient Boosting for better accuracy")
print("  4. Handle class imbalance (SMOTE / class_weight='balanced')")
print("  5. Export the model using joblib for deployment")
print("\n" + "=" * 55)
print("  Pipeline Complete!")
print("=" * 55)

=======================================================
  FINAL SUMMARY
=======================================================

  Best Performing Model : Random Forest

  Random Forest:
    Accuracy    : 91.89%
    ROC-AUC     : 0.9525
    CV Accuracy : 88.38%

  [NEXT STEPS]
  1. Load the actual TRAINING dataset with Loan_Status labels
  2. Tune hyperparameters (GridSearchCV / RandomizedSearchCV)
  3. Try XGBoost or Gradient Boosting for better accuracy
  4. Handle class imbalance (SMOTE / class_weight='balanced')
  5. Export the model using joblib for deployment

=======================================================
  Pipeline Complete!
=======================================================